CREATE TABLE ORDERS(
	ID_ORDER CHAR(10) PRIMARY KEY,
	NAME_CUSTOMER NVARCHAR(50),
	EMAIL NVARCHAR(50),
	PHONE INT
)
GO

CREATE TABLE TYPESS(
	ID_TYPE CHAR(10) PRIMARY KEY,
	TYPE_NAMES NVARCHAR(50),
	STATUSS NVARCHAR(50),
)
GO

CREATE TABLE COLORS (
	ID_COLOR CHAR(10) PRIMARY KEY,
	COLOR_NAMES NVARCHAR(50),
	STATUSS NVARCHAR(50),
	ID_TYPE CHAR(10) REFERENCES TYPESS(ID_TYPE),
)
GO

create table SHOES(
	ID_SHOES CHAR(10) PRIMARY KEY,
	SHOES_NAME NVARCHAR(50),
	PRICE SMALLMONEY,
	DESCRIPTIONS NVARCHAR(50),
	ID_TYPE CHAR(10) REFERENCES TYPESS(ID_TYPE),
	ID_ORDER CHAR(10) REFERENCES ORDERS(ID_ORDER)
)
GO

CREATE TABLE SIZES(
	ID_SIZE CHAR(10) PRIMARY KEY,
	SIZE_NAME NVARCHAR(50),
	STATUSS NVARCHAR(50),
	ID_TYPE CHAR(10) REFERENCES TYPESS(ID_TYPE),
)
GO

CREATE TABLE SHOESWITHSIZE(
	ID_SIZE CHAR(10)REFERENCES SIZES(ID_SIZE)  ,
	ID_SHOES CHAR(10) REFERENCES SHOES(ID_SHOES),
	PRIMARY KEY (ID_SIZE,ID_SHOES)
)
GO

CREATE TABLE SIZESWITHCOLORS(
	ID_SIZE CHAR(10)REFERENCES SIZES(ID_SIZE)  ,
	ID_COLOR CHAR(10)REFERENCES COLORS(ID_COLOR)
	PRIMARY KEY (ID_SIZE,ID_COLOR)
)
GO

CREATE TABLE SHOESWITHCOLORS(
	ID_SHOES CHAR(10)REFERENCES SHOES(ID_SHOES)  ,
	ID_COLOR CHAR(10)REFERENCES COLORS(ID_COLOR),
	PRIMARY KEY (ID_SHOES,ID_COLOR)
)
GO

CREATE TABLE IMAGES(
	ID_IMAGES CHAR(10) PRIMARY KEY,
	IMAGE_NAME NVARCHAR(50),
	ID_SHOES CHAR(10) REFERENCES SHOES(ID_SHOES),
)
GO

CREATE TABLE ORDER_DETAIL(
	ID_ORDER_DETAIL CHAR(10) PRIMARY KEY,
	LOCAL NVARCHAR(50),
	CODESALE CHAR(10),
	TOTAL_PRICE SMALLMONEY,
	STATUSS NVARCHAR(50),
	ID_ORDER CHAR(10) REFERENCES ORDERS(ID_ORDER),
)
GO