USE WebShoes
go
CREATE TABLE ORDERS(
	ID_ORDER INT IDENTITY(1,1) PRIMARY KEY,
	NAME_CUSTOMER NVARCHAR(50),
	EMAIL NVARCHAR(50),
	PHONE INT
)
GO

CREATE TABLE TYPESS(
	ID_TYPE INT IDENTITY(1,1) PRIMARY KEY,
	TYPE_NAMES NVARCHAR(50),
	STATUSS NVARCHAR(50),
)
GO

CREATE TABLE COLORS (
	ID_COLOR INT IDENTITY(1,1) PRIMARY KEY,
	COLOR_NAMES NVARCHAR(50),
	STATUSS NVARCHAR(50),
	ID_TYPE INT  REFERENCES TYPESS(ID_TYPE),
)
GO

create table SHOES(
	ID_SHOES INT IDENTITY(1,1) PRIMARY KEY,
	SHOES_NAME NVARCHAR(50),
	PRICE SMALLMONEY,
	DESCRIPTIONS NVARCHAR(50),
	ID_TYPE INT REFERENCES TYPESS(ID_TYPE),
	ID_ORDER INT REFERENCES ORDERS(ID_ORDER)
)
GO

CREATE TABLE SIZES(
	ID_SIZE INT IDENTITY(1,1) PRIMARY KEY,
	SIZE_NAME NVARCHAR(50),
	STATUSS NVARCHAR(50),
	ID_TYPE INT REFERENCES TYPESS(ID_TYPE),
)
GO

CREATE TABLE SHOESWITHSIZE(
	ID_SIZE INT REFERENCES SIZES(ID_SIZE)  ,
	ID_SHOES INT REFERENCES SHOES(ID_SHOES),
	PRIMARY KEY (ID_SIZE,ID_SHOES)
)
GO

CREATE TABLE SIZESWITHCOLORS(
	ID_SIZE INT REFERENCES SIZES(ID_SIZE)  ,
	ID_COLOR INT REFERENCES COLORS(ID_COLOR)
	PRIMARY KEY (ID_SIZE,ID_COLOR)
)
GO

CREATE TABLE SHOESWITHCOLORS(
	ID_SHOES INT REFERENCES SHOES(ID_SHOES)  ,
	ID_COLOR INT REFERENCES COLORS(ID_COLOR),
	PRIMARY KEY (ID_SHOES,ID_COLOR)
)
GO

CREATE TABLE IMAGES(
	ID_IMAGES INT IDENTITY(1,1) PRIMARY KEY,
	IMAGE_NAME NVARCHAR(50),
	ID_SHOES INT REFERENCES SHOES(ID_SHOES),
)
GO

CREATE TABLE ORDER_DETAIL(
	ID_ORDER_DETAIL INT IDENTITY(1,1) PRIMARY KEY,
	LOCAL NVARCHAR(50),
	CODESALE CHAR(10),
	TOTAL_PRICE SMALLMONEY,
	STATUSS NVARCHAR(50),
	ID_ORDER INT REFERENCES ORDERS(ID_ORDER),
)
GO

CREATE TABLE BRANDS(
	ID_BRAND INT IDENTITY(1,1) PRIMARY KEY,
	BRANDS_NAME NVARCHAR(50),
	ID_SHOES INT REFERENCES SHOES(ID_SHOES)
)

ALTER TABLE dbo.SHOES ALTER COLUMN PRICE MONEY

SELECT * FROM dbo.SHOES

ALTER TABLE dbo.SHOES ALTER COLUMN  ID_BRAND INT 

ALTER TABLE dbo.BRANDS DROP CONSTRAINT FK__BRANDS__ID_SHOES__59063A47

ALTER TABLE dbo.SHOES add SL INT, IMG CHAR(20)


UPDATE dbo.SHOES
SET ID_TYPE = 4
WHERE ID_SHOES BETWEEN 19 AND 24

