CREATE TABLE NHANVIEN(
MANV CHAR(10) PRIMARY KEY,
HOTENNV NVARCHAR(50),
NGAYSINH DATE,
GIOITINH CHAR(3),
DIACHI NVARCHAR(50),
SDT CHAR(10),
CHUCVU NVARCHAR(20),
LUONG INT,
MATKHAU CHAR(20)
)

CREATE TABLE KHACHHANG(
MAKH CHAR(10) PRIMARY KEY,
HOTENKH NVARCHAR(50),
NSKH DATE,
GTKH CHAR(3),
DCKH NVARCHAR(50),
SDTKH CHAR(10),
DIEM INT
)

CREATE TABLE HOADON(
MAHD CHAR(10) PRIMARY KEY,
NGAYLAP DATE,
MAKH CHAR(10) REFERENCES KHACHHANG(MAKH),
MANV CHAR(10) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE MATHANG(
MAHANG CHAR(10) PRIMARY KEY,
TENHANG NVARCHAR(50),
SOLUONG INT,
DONGIA INT
)

CREATE TABLE CHITIETHD(
MAHD CHAR(10) REFERENCES HOADON(MAHD),
MAHANG CHAR(10) REFERENCES MATHANG(MAHANG),
SOLUONG INT,
DONGIA INT,
PRIMARY KEY(MAHD,MAHANG)
)

CREATE TABLE HANGSX(
MANSX CHAR(10) PRIMARY KEY,
TENNSX NVARCHAR(20),
XUATXU NVARCHAR(20),
WEBSITE VARCHAR(50)
)

